name: 项目发布
on:
  push: # 监听调用时机为push事件
    branches: ["main"] # 监听master分支

jobs:
  release:
    runs-on: ubuntu-latest # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 上传模型
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "models"
          target: "/${{secrets.SSH_USERNAME}}/Projects/.oml2d_models_temp/"
          rm: true
          strip_components: 1

      - name: 执行远程脚本命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf /${{ secrets.SSH_USERNAME }}/Projects/oml2d-models
            mkdir -p /${{ secrets.SSH_USERNAME }}/Projects/oml2d-models
            cp -rf /${{ secrets.SSH_USERNAME }}/Projects/.oml2d_models_temp/*  /${{ secrets.SSH_USERNAME }}/Projects/oml2d-models
